package com.learnwithhamster.service.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CourseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseAllPropertiesEquals(Course expected, Course actual) {
        assertCourseAutoGeneratedPropertiesEquals(expected, actual);
        assertCourseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseAllUpdatablePropertiesEquals(Course expected, Course actual) {
        assertCourseUpdatableFieldsEquals(expected, actual);
        assertCourseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseAutoGeneratedPropertiesEquals(Course expected, Course actual) {
        assertThat(actual)
            .as("Verify Course auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseUpdatableFieldsEquals(Course expected, Course actual) {
        assertThat(actual)
            .as("Verify Course relevant properties")
            .satisfies(a -> assertThat(a.getCourseTitle()).as("check courseTitle").isEqualTo(expected.getCourseTitle()))
            .satisfies(a -> assertThat(a.getCourseDescription()).as("check courseDescription").isEqualTo(expected.getCourseDescription()))
            .satisfies(a -> assertThat(a.getCoursePrice()).as("check coursePrice").isEqualTo(expected.getCoursePrice()))
            .satisfies(a -> assertThat(a.getCourseLevel()).as("check courseLevel").isEqualTo(expected.getCourseLevel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseUpdatableRelationshipsEquals(Course expected, Course actual) {
        assertThat(actual)
            .as("Verify Course relationships")
            .satisfies(a -> assertThat(a.getLessons()).as("check lessons").isEqualTo(expected.getLessons()))
            .satisfies(a -> assertThat(a.getPrograms()).as("check programs").isEqualTo(expected.getPrograms()));
    }
}
