package com.learnwithhamster.service.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DisciplineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisciplineAllPropertiesEquals(Discipline expected, Discipline actual) {
        assertDisciplineAutoGeneratedPropertiesEquals(expected, actual);
        assertDisciplineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisciplineAllUpdatablePropertiesEquals(Discipline expected, Discipline actual) {
        assertDisciplineUpdatableFieldsEquals(expected, actual);
        assertDisciplineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisciplineAutoGeneratedPropertiesEquals(Discipline expected, Discipline actual) {
        assertThat(actual)
            .as("Verify Discipline auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisciplineUpdatableFieldsEquals(Discipline expected, Discipline actual) {
        assertThat(actual)
            .as("Verify Discipline relevant properties")
            .satisfies(a -> assertThat(a.getDisciplineName()).as("check disciplineName").isEqualTo(expected.getDisciplineName()))
            .satisfies(a ->
                assertThat(a.getDisciplineDescription()).as("check disciplineDescription").isEqualTo(expected.getDisciplineDescription())
            )
            .satisfies(a -> assertThat(a.getDisciplinePrice()).as("check disciplinePrice").isEqualTo(expected.getDisciplinePrice()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisciplineUpdatableRelationshipsEquals(Discipline expected, Discipline actual) {
        assertThat(actual)
            .as("Verify Discipline relationships")
            .satisfies(a -> assertThat(a.getPrograms()).as("check programs").isEqualTo(expected.getPrograms()));
    }
}
