package com.learnwithhamster.service.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProgramAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgramAllPropertiesEquals(Program expected, Program actual) {
        assertProgramAutoGeneratedPropertiesEquals(expected, actual);
        assertProgramAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgramAllUpdatablePropertiesEquals(Program expected, Program actual) {
        assertProgramUpdatableFieldsEquals(expected, actual);
        assertProgramUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgramAutoGeneratedPropertiesEquals(Program expected, Program actual) {
        assertThat(actual)
            .as("Verify Program auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgramUpdatableFieldsEquals(Program expected, Program actual) {
        assertThat(actual)
            .as("Verify Program relevant properties")
            .satisfies(a -> assertThat(a.getProgramName()).as("check programName").isEqualTo(expected.getProgramName()))
            .satisfies(a -> assertThat(a.getProgramDescription()).as("check programDescription").isEqualTo(expected.getProgramDescription())
            )
            .satisfies(a -> assertThat(a.getProgramPrice()).as("check programPrice").isEqualTo(expected.getProgramPrice()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgramUpdatableRelationshipsEquals(Program expected, Program actual) {
        assertThat(actual)
            .as("Verify Program relationships")
            .satisfies(a -> assertThat(a.getCourses()).as("check courses").isEqualTo(expected.getCourses()))
            .satisfies(a -> assertThat(a.getDisciplines()).as("check disciplines").isEqualTo(expected.getDisciplines()));
    }
}
