package com.learnwithhamster.service.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResourceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceAllPropertiesEquals(Resource expected, Resource actual) {
        assertResourceAutoGeneratedPropertiesEquals(expected, actual);
        assertResourceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceAllUpdatablePropertiesEquals(Resource expected, Resource actual) {
        assertResourceUpdatableFieldsEquals(expected, actual);
        assertResourceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceAutoGeneratedPropertiesEquals(Resource expected, Resource actual) {
        assertThat(actual)
            .as("Verify Resource auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceUpdatableFieldsEquals(Resource expected, Resource actual) {
        assertThat(actual)
            .as("Verify Resource relevant properties")
            .satisfies(a -> assertThat(a.getResourceName()).as("check resourceName").isEqualTo(expected.getResourceName()))
            .satisfies(a ->
                assertThat(a.getResourceDescription()).as("check resourceDescription").isEqualTo(expected.getResourceDescription())
            )
            .satisfies(a -> assertThat(a.getResourceURL()).as("check resourceURL").isEqualTo(expected.getResourceURL()))
            .satisfies(a ->
                assertThat(a.getResourcePreviewImage()).as("check resourcePreviewImage").isEqualTo(expected.getResourcePreviewImage())
            )
            .satisfies(a -> assertThat(a.getResourceType()).as("check resourceType").isEqualTo(expected.getResourceType()))
            .satisfies(a -> assertThat(a.getWeight()).as("check weight").isEqualTo(expected.getWeight()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceUpdatableRelationshipsEquals(Resource expected, Resource actual) {
        assertThat(actual)
            .as("Verify Resource relationships")
            .satisfies(a -> assertThat(a.getDiscipline()).as("check discipline").isEqualTo(expected.getDiscipline()))
            .satisfies(a -> assertThat(a.getProgram()).as("check program").isEqualTo(expected.getProgram()))
            .satisfies(a -> assertThat(a.getCourse()).as("check course").isEqualTo(expected.getCourse()))
            .satisfies(a -> assertThat(a.getLesson()).as("check lesson").isEqualTo(expected.getLesson()));
    }
}
